version: '3.8'

services:
  mysql-server:
    image: mysql:8.0
    platform: linux/amd64
    container_name: mysql-server
    environment:
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix_pwd"
      MYSQL_ROOT_PASSWORD: "root_pwd"
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8
      --collation-server=utf8_bin
    ports:
      - "3306:3306"
    networks:
      zabbix-net:
        ipv4_address: 172.20.240.2
    restart: unless-stopped

  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway:alpine-6.0.0
    platform: linux/amd64
    container_name: zabbix-java-gateway
    networks:
      zabbix-net:
        ipv4_address: 172.20.240.3
    restart: unless-stopped

  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:alpine-6.0.0
    platform: linux/amd64
    container_name: zabbix-server-mysql
    environment:
      DB_SERVER_HOST: "mysql-server"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix_pwd"
      MYSQL_ROOT_PASSWORD: "root_pwd"
      ZBX_JAVAGATEWAY: "zabbix-java-gateway"
    ports:
      - "10051:10051"
    networks:
      zabbix-net:
        ipv4_address: 172.20.240.4
    depends_on:
      - mysql-server
      - zabbix-java-gateway
    restart: unless-stopped

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.0.0
    platform: linux/amd64
    container_name: zabbix-web-nginx-mysql
    environment:
      ZBX_SERVER_HOST: "zabbix-server-mysql"
      DB_SERVER_HOST: "mysql-server"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix_pwd"
      MYSQL_ROOT_PASSWORD: "root_pwd"
    ports:
      - "8080:8080"
    networks:
      zabbix-net:
        ipv4_address: 172.20.240.5
    depends_on:
      - zabbix-server-mysql
    restart: unless-stopped

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-6.0.0
    platform: linux/amd64
    container_name: zabbix-agent
    environment:
      ZBX_HOSTNAME: "host-01"
      ZBX_SERVER_HOST: "172.20.240.4"
      ZBX_SERVER_PORT: 10051
    volumes:
      - zabbix_agent:/etc/zabbix
    ports:
      - "10050:10050"
    networks:
      zabbix-net:
        ipv4_address: 172.20.240.6
    privileged: true
    restart: unless-stopped

networks:
  zabbix-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.240.0/24
          ip_range: 172.20.240.0/24

volumes:
  zabbix_agent:
    driver: local
