services:

  wordpress:
    container_name: CVE-2024-10924
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - 1337:80
    environment:
      WORDPRESS_DEBUG: 1
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb

  db:
    container_name: CVE-2024-10924-mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - CVE-2024-10924-mysql:/var/lib/mysql

volumes:
  CVE-2024-10924-mysql:
